name: Linux-aarch64-musl

env:
  DEBUG: 'napi:*'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: stable - aarch64-unknown-linux-gnu - node@16
    runs-on: ubuntu-latest

    steps:
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: npm-cache-linux-aarch64-gnu-node@16

      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build

      - name: Cross build native tests
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
          options: -v ${{ github.workspace }}:/napi-rs -w /napi-rs
          run: |
            yarn build
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc
            yarn workspace compat-mode-examples build --target aarch64-unknown-linux-musl
            yarn workspace examples build --target aarch64-unknown-linux-musl

      - name: Setup and run tests
        uses: docker://multiarch/alpine:aarch64-latest-stable
        with:
          args: >
            sh -c "
              apk add nodejs yarn && \
              yarn test
            "
